# Generated by Django 3.2 on 2022-08-04 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='skill_title',
            new_name='skills',
        ),
    ]
