# Generated by Django 3.2 on 2022-08-02 01:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20220802_0720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='M',
        ),
    ]
