# Generated by Django 3.2 on 2022-08-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_userimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
