# Generated by Django 3.2 on 2022-08-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_userinfo_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
    ]
