# Generated by Django 3.2 on 2022-08-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_userskill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='skills',
            field=models.ManyToManyField(to='base.UserSkill'),
        ),
    ]
