# Generated by Django 3.2 on 2022-08-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_userskill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.AddField(
            model_name='userskill',
            name='user',
            field=models.ManyToManyField(to='base.UserInfo'),
        ),
    ]
