# Generated by Django 3.2 on 2022-08-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20220803_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
    ]
