# Generated by Django 3.2 on 2022-08-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_userskill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
    ]
