# Generated by Django 3.2 on 2022-08-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20220804_0133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSkill',
            new_name='Skill',
        ),
        migrations.CreateModel(
            name='UserSkillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.ManyToManyField(to='base.Skill')),
            ],
        ),
    ]
