# Generated by Django 3.2 on 2022-08-04 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20220804_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskillinfo',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='UserSkillInfo',
        ),
    ]
